export const transaction = {
	orderId: "#281209",
	orderDate: new Date(),
	orderAmt: 1278.23,
	fees: 22,
};

export const transactions = [
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
	transaction,
];
